apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-toggle-config
data:
  FEATURE_DARK_MODE: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: mariadb-configmap
data:
 db-load-script.sql: |
  CREATE DATABASE $(DB_NAME);
  CREATE USER '$(DB_USER)'@'$(DB_HOST)' IDENTIFIED BY '$(MARIADB_PASSWORD)'';
  GRANT ALL PRIVILEGES ON $(DB_NAME).* TO '$(DB_USER)'@'%';
  FLUSH PRIVILEGES;
  USE $(DB_NAME);
  CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;
  INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");