apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo
  namespace: default
spec:
  secretName: demo
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: e2ae037a-56b6-4f18-be50-b51bc32ec6e1.lb.civo.com
  dnsNames:
  - e2ae037a-56b6-4f18-be50-b51bc32ec6e1.lb.civo.com