apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-my-web-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecom-app
  template:
    metadata:
      labels:
        app: ecom-app
    spec:
      containers:
        - name: ecom-web
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: vishnumohanan/ecom-web:latest
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: 80
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: 80
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-feature-toggle-config
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}-database-svc # MariaDB Service name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER # Database user from secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-my-service
spec:
  type: LoadBalancer
  selector:
    app: ecom-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-web-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-my-web-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
